name: GEN
on:
  schedule:
    - cron: "0 6 * * 2"
    - push
jobs:
  CloudList:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
#      - name: Set up Python 3.8
#        uses: actions/setup-python@v2
#        with:
#          python-version: "3.8"
      - name: Install dependencies
        run: |
          bash inst-gen.sh
      - name: generate
        run: |
          echo "starting"
          test -e lists || mkdir lists
          octet_one=9
          octet_two=9
          octet_three=9
          test -e lists/$octet_one || mkdir lists/$octet_one
          test -e lists/${octet_one}/${octet_one}.${octet_two} || mkdir lists/${octet_one}/${octet_one}.${octet_two}
          time (echo {0..254}.{octet_three}.${octet_two}.${octet_one}.in-addr.arpa |sed 's/ /\n/g'|/tmp/dns -r /tmp/resolvers -t PTR -|grep PTR|grep -v PTR$ > lists/${octet_one}/${octet_one}.${octet_two}/${octet_one}.${octet_two}.${octet_three})
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: add stuff
          title: add rdns
          body: rdns - Update available list
          base: main
          labels: automated-pr, automerge
#          branch: cloud-update-advanced-params
          delete-branch: true