name: Enable Auto Merging

on:  
  push:
  pull_request:
    branches:
      - pages

jobs:  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: kenhowardpdx/auto-merge-action@v1
        if: ${{ github.actor == 'dependabot[bot]' }}