name: Enable Auto Merging..

on:  
#  push:
  pull_request:
#    branches:
#      - pages
  pull_request_target:
    branches:
      - pages

jobs:  
  merge:
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: KeisukeYamashita/auto-pull-request-merge@v1
        with:
          intervalSeconds: 10
          timeoutSeconds: 30
          labels: "automerge"