name: Enable Auto Merging

on:  
#  push:
  pull_request:
    branches:
      - pages

jobs:  
  test:
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"