name: Enable Auto Merging

on:  
#  push:
  pull_request:
    branches:
      - pages
  pull_request_target:
    branches:
      - pages

jobs:  
  merge:
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "automerge,!work in progress"
          BASE_BRANCHES: "pages"
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "pull-request-description.."
          MERGE_FORKS: "false"
          MERGE_RETRIES: "5"
          MERGE_RETRY_SLEEP: "10000"
          MERGE_REQUIRED_APPROVALS: "0"
          MERGE_DELETE_BRANCH: "true"
          MERGE_REMOVE_LABELS: "automerge"