name: GEN
on:
  push:
    branches:
      - 'master'
      - 'main'
  schedule:
    - cron: '0 0 1 * *'
jobs:
  generate:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      matrix:
        otwo: [3,9]
        othree: [8,9]
        #arch: [linux_SLASH_amd64]
        #include:
        #  - os: alpine
        #    arch: linux_SLASH_386
        #  - os: alpine
        #    arch: linux_SLASH_arm_SLASH_v6
        #  - os: ubuntu-bionic
        #    arch: linux_SLASH_386
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          ref: 'pages'
          
      - name: List Files
        run: |
          find -type f      
#      - name: Set up Python 3.8
#        uses: actions/setup-python@v2
#        with:
#          python-version: "3.8"
      - name: Install dependencies
        run: |
          bash inst-gen.sh
      - name: Run thingy. 
        run: |
          git config --global user.email "actions@github.com" && git config --global user.name "you@example.com"
          echo "starting... _${{ matrix.otwo }}_${{ matrix.othree }}"
          git checkout -b mybranch_to_merge_${{ matrix.otwo }}_${{ matrix.othree }} pages
          git branch
          git pull --rebase  origin mybranch_to_merge_${{ matrix.otwo }}_${{ matrix.othree }}  || ( git pull   origin mybranch_to_merge_${{ matrix.otwo }}_${{ matrix.othree }} --allow-unrelated-histories || true ) 
          bash gen.sh 9 ${{ matrix.otwo }} ${{ matrix.othree }} || true 
          git add -A && git commit -m "automerge mybranch_to_merge_${{ matrix.otwo }}_${{ matrix.othree }}" && git push --set-upstream origin mybranch_to_merge_${{ matrix.otwo }}_${{ matrix.othree }}
      - name: create pull request
        run: gh pr create -B pages -H mybranch_to_merge_${{ matrix.otwo }}_${{ matrix.othree }} --label automerge --title 'Merge mybranch_to_merge_${{ matrix.otwo }}_${{ matrix.othree }} into base_branch' --body 'Created by Github action'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  merge:
    needs: generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          ref: 'pages'
      - name: Enable Pull Request Automerge
        run: gh pr list && gh pr list |cut  -f1 | while read a ;do gh pr merge --delete-branch --squash --auto "$a";done
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}