name: GEN
on:
  push:
    branches:
      - 'master'
      - 'main'
  schedule:
    - cron: '0 0 1 * *'
jobs:
  generate:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      matrix:
        oone: [1,2,3,4,5,6,7,8]
        otwo: [1,2]
        #arch: [linux_SLASH_amd64]
        #include:
        #  - os: alpine
        #    arch: linux_SLASH_386
        #  - os: alpine
        #    arch: linux_SLASH_arm_SLASH_v6
        #  - os: ubuntu-bionic
        #    arch: linux_SLASH_386
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          ref: 'pages'
          
      - name: List Files
        run: |
          find -type f      
#      - name: Set up Python 3.8
#        uses: actions/setup-python@v2
#        with:
#          python-version: "3.8"
      - name: Install dependencies
        run: |
          bash inst-gen.sh
      - name: Run thingy... 
        run: |
          git config --global user.email "actions@github.com" && git config --global user.name "you@example.com"
          echo "starting... _${{ matrix.oone }}_${{ matrix.otwo }}"
          git checkout -b mybranch_to_merge_${{ matrix.oone }}_${{ matrix.otwo }} pages
          git branch
          git pull --rebase  origin mybranch_to_merge_${{ matrix.oone }}_${{ matrix.otwo }}  || ( git pull   origin mybranch_to_merge_${{ matrix.oone }}_${{ matrix.otwo }} --allow-unrelated-histories || git rebase --skip|| true ) 
          curl https://raw.githubusercontent.com/TheFoundation/ipv4reverse/master/gen.sh > gen.sh
          bash gen.sh 9 ${{ matrix.oone }} ${{ matrix.otwo }} || true 
          git add -A && git commit -m "automerge mybranch_to_merge_${{ matrix.oone }}_${{ matrix.otwo }}" || true 
          echo "none" > gitres
          bash -c 'git push --set-upstream origin mybranch_to_merge_${{ matrix.oone }}_${{ matrix.otwo }} &>gitres || true' || true 
          bash -c 'grep "othing to commit" .gitres || true' || true 
          exit 0
      - name: create pull request
        run: gh pr create -B pages -H mybranch_to_merge_${{ matrix.oone }}_${{ matrix.otwo }} --label automerge --title 'Merge mybranch_to_merge_${{ matrix.oone }}_${{ matrix.otwo }} into base_branch' --body 'Created by Github action' || true 
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  merge:
    needs: generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          ref: 'pages'
      - name: Enable Pull Request Automerge
        run: gh pr list && gh pr list |cut  -f1 | while read a ;do gh pr merge --delete-branch --squash --auto "$a";done
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}